# Generated by Django 3.0.7 on 2020-07-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='areaofvol',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='district',
        ),
    ]
