# Generated by Django 3.0.7 on 2020-07-22 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0003_auto_20200722_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='userprofile',
        ),
    ]
