# Generated by Django 3.0.7 on 2020-07-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0004_remove_userpost_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='areaofvol',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
