# Generated by Django 3.0.7 on 2020-07-22 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0006_userpost_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
