# Generated by Django 3.0.7 on 2020-07-22 20:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0007_auto_20200722_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='userpost',
            name='upvotes',
            field=models.ManyToManyField(related_name='luserprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
