# Generated by Django 3.0.7 on 2020-07-22 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0008_auto_20200722_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='luserprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
